### ISSUE TITLE
Link to documentation returns a 403

### ISSUE THREAD

**Issue by plorent** [aws-solutions/aws-data-lake-solution#49]
The link in the documentation results in a 403 Forbidden: http://docs.awssolutionsbuilder.com/data-lake/
Documentation page: https://docs.aws.amazon.com/solutions/latest/data-lake-solution/deployment.html

**Comment by yokharian** [comment]
**https://web.archive.org/web/20220127182003/http://docs.awssolutionsbuilder.com/data-lake/**

**Comment by plorent** [comment]
The issue got resolved
